animal:
  name:
    fishNames: fish11,fish21,fish
    herbivoresNames: herb,myHerbivores
    petNames: pet1,pet2,pet3
    predatorNames: predator, predatorbrator
spring:
  main:
    allow-bean-definition-overriding: true