animal:
  name:
    fishNames: fish11,fish21,fish
    herbivoresNames: herb,myHerbivores
    petNames: pet1,pet2,pet3
    predatorNames: predator, predatorbrator
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=animals
    username: postgres
    password: Gukm5998
    dbcp2:
      default-schema: animals
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
server:
  port: 8090