animal:
  name:
    fishNames: guppi,fish21,fish
    herbivoresNames: black,myHerbivores
    petNames: pet1,pet2,pet3
    predatorNames: predator, predatorbrator
spring:
  main:
    allow-bean-definition-overriding: true